### PR TITLE
feat: add order of the JWT source header/cookie/query as config

### PR DESCRIPTION
**Pull request by simonpahl**
With this PR it is posible to control the order how the JWT is resolved from header, cookie or query parameter.

### CODE REVIEW

**Review by eshepelyuk — COMMENTED** [review]
1. First issue is missing unit tests.
2. Second I'd like propose a deeper change, instead of having several parameters to configure order and source of token extraction - i think about boling it down to one parameter that could look like
```yaml
JwtSources:
- bearer:MyAuth # value from http header in format Bearer: TOKEN
- header:MyJwt # plain value of http header
- cookie:MyCookie # plain value of cookie
- query:MyQuery # plain value of query string parameter
```

WDYT ?

**Comment by simonpahl** [comment]
I like the idea and i am working on it. I've pushed my progress so far. One problem is preserving the order, als pure maps can't do that. The current idea for the config is
`JwtSources:
  - type: bearer
     key: Authorization
...
`

**Comment by simonpahl** [comment]
Ok, i think it is done.

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
1. can you mark deprecated parameters also in plugin code, i think godoc should have some sort of deprecation tags.
2. should not the default value of order be initialized in CreateConfig function ?

**Comment by simonpahl** [comment]
1. I have marked it like described here https://go.dev/wiki/Deprecated
2. I don't think i could implement the backwards copatibility to JwtCookieKey and JwtQueryKey this way

**Comment by eshepelyuk** [comment]
> 1. I have marked it like described here https://go.dev/wiki/Deprecated
> 2. I don't think i could implement the backwards copatibility to JwtCookieKey and JwtQueryKey this way

understood, thanks

**Review by eshepelyuk — APPROVED** [review]

**Comment by eshepelyuk** [comment]
Thanks for anither great contributions, availablein 0.9.0 version.

**Pull request merged**
